house:
  price: 1000000
  loan_period: 35
  current_interest: 0.044 # percent convert to decimal places
  percentage_loan: 0.9 # percent convert to decimal places
  expected_annual_increment: 0.002 # percent convert to decimal
  starting_year: 2024

export_data:
  destination: 
    monthly: "monthly.txt"
    yearly: "yearly.txt"
